#!/bin/bash

# A floating keyboard to show current key layout.

# TODO: get rest of keycodes
get_keycodes(){
	letter_codes=($(dumpkeys | grep -oP "\d\d(?=\s=\s[+]\w)"))
	letter_order=($(dumpkeys | grep -oP "(?<=\d\d\s=\s[+])\w"))
	# put letter at keys[keycode]
	for k in ${!letter_order[@]}; do
		keys["${letter_codes[$k]}"]="${letter_order[$k]}"
	done
	keys[$(dumpkeys | grep -o "\w\w(?=\s=\ssemicolon)")]=";"
}
get_keycodes

# TODO: word to symbol func

# TODO: display keyboard
display_keys(){
	lines[0]=""
	screen_centre=$(($(tput cols)/2))
	let key_start_col=$(( screen_centre - 12 ))
	# tput cuu1
	tput sc
	for i in ${!lines[@]}; do
		tput cup $i $key_start_col
		tput el1
		tput el
		echo -e "${lines[$i]}"
	done
	# clear line below shown keys
	tput el1
	tput el
	tput rc
}
display_keys

prompt_command(){
	# get keycodes each call if --recheck set
	if [ $1 == "-r" -o "--recheck" ]
	then get_keycodes
	fi
	display_keys
}

# fix display
## TODO: if prompt_command not in PROMPT_COMMAND
# PROMPT_COMMAND=prompt_command
